# Parameters for the model_crane environment

# Add the file_directory of input poitcloud folder 
file_directory: /media/aisl2/aisl_data/catkin_ws/src/latest_crane/map_optimization/input_pointcloud_data/kobelco_2023/


# Parameters for ground_plane
ground_angle_degree: 10.0
ground_distance_threshold: .5
min_ground_plane_size: 8477
ground_plane_cluster_Tolerance: 1.5  # Adjust this value based on the density of your point cloud

# Parameters for wall_plane
wall_distance_threshold: 0.5
wall_angle_degree: 60
min_wall_plane_size: 2432

ground_plane_cluster_extraction: false