# Parameters for the model_crane environment

# Add the file_directory of input poitcloud folder 
file_directory: /home/aisl2/catkin_ws/src/latest_crane/map_optimization/input_pointcloud_data/model_crane_exp_environment/


# Parameters for ground_plane
ground_angle_degree: 25.0
ground_distance_threshold: 0.15
min_ground_plane_size: 9990
ground_plane_cluster_Tolerance: 5.5  # Adjust this value based on the density of your point cloud

# Parameters for wall_plane
wall_distance_threshold: 0.1
wall_angle_degree: 3.0
min_wall_plane_size: 1989

ground_plane_cluster_extraction: false